### ISSUE TITLE
Add /categories/:id/products route

### ISSUE THREAD

**Issue by iliubinskii** [iliubinskii/bootcamp-products-api#17]
Each product has a "categories" field that holds an array of categories where it belongs.

**Comment by TheTomre** [comment]
Maybe it should be /products/:id/categories then?

**Comment by iliubinskii** [comment]
The route's string is right:
```
/categories/:id/products
```

This is typical online store:
https://www.amazon.co.uk/computers-accessories/b?ie=UTF8&node=340831031
See that it has a page that lists all products in the category "Computers accessories"?
This page needs a route like this: "/categories/:id/products" 

The route that you propose "/products/:id/categories" can also be useful for product page:
https://www.amazon.co.uk/fire-7-tablet-7-display-16-gb-2022-release/dp/B099HL86MQ?ref_=Oct_d_omg_d_340831031_1&pd_rd_w=l0wrp&content-id=amzn1.sym.11b6cb5a-7f19-45f3-972a-cdeff1f927d2&pf_rd_p=11b6cb5a-7f19-45f3-972a-cdeff1f927d2&pf_rd_r=W9600X91RM0GTWZN0J56&pd_rd_wg=zDac4&pd_rd_r=3c33fdcf-e292-4969-8fa1-fa545c413a53&pd_rd_i=B099HL86MQ
to show the list of categories to which product belongs. But I would rather include extended category info in this route to save one API request:
```
/products/:id?extended-categories-info=true
```
