### ISSUE TITLE
users/service.js does not distinguish missing data (404) and error (500) conditions

### ISSUE THREAD

**Issue by iliubinskii** [iliubinskii/bootcamp-products-api#24]
Suggested fix:

getUserById - Do not catch errors
createUser - If user already exists (error.code === 11000) return null, otherwise rethrow
updateUser - Do not catch errors 
deleteUser - Do not catch errors

**Comment by TheTomre** [comment]
please merge my las pull request (https://github.com/iliubinskii/bootcamp-products-api/pull/34) and say if we still need to solve this issue
