### ISSUE TITLE
Make users service reusable by all 3 routers

### ISSUE THREAD

**Issue by iliubinskii** [iliubinskii/bootcamp-products-api#6]
Use generator function that takes Mongoose model as a param

Also inject logger instead of importing it statically

```js
function createMongodbService(mongooseModel, logger) {
  return () => ({
    getItems, getItemById, createItem, deleteItem
  });
}
```

**Comment by iliubinskii** [comment]
Place it all in "src/crud" folder.

**Comment by TheTomre** [comment]
https://github.com/iliubinskii/bootcamp-products-api/pull/31
