### ISSUE TITLE
Add try catch to all async controllers

### ISSUE THREAD

**Issue by iliubinskii** [iliubinskii/bootcamp-products-api#9]
Otherwise errors in async controller crash server even with error handling route.

```js
async myAsyncController(req, res, next)  {
      try {
        ...
      } catch (err) {
        next(err);
      }
    }
```

**Comment by iliubinskii** [comment]
Only for users and categories. Does not apply to products folder.

**Comment by TheTomre** [comment]
I made a reusable controllers model so i  it will work everywhere  now.
